### ISSUE TITLE
Update Senegal, Cameroon, Burkina and Haiti support

### ISSUE THREAD

**Issue by rjmangubat23** [idpass/smartscanner-mrz-parser#5]
## Current Behaviour

- No clear specific checking Cameroon and Burkina support
- Senegal is already added 

## Expected Behaviour

- Update or check if Senegal, Cameroon, Burkina and Haiti support is working properly

**Comment by typelogic** [comment]
Result of inspections. 

**Senegal:**
- Doc# at index range 5-22 of row 0
- Dob, exp and composite check-digits is conformant to standard as usual.
Conclusion: It is the the Doc# that needs index adjustment.

**Cameroon:**
- Doc#, Dob, exp and composite check-digits all conforms to standard as usual
Conclusion: No unusual index change is neeeded

**Burkina:**
- Doc#, Dob, exp and composite check-digits all conforms to standards as usual.
Conclusion: No unusual index change is needed.

**Comment by rjmangubat23** [comment]
Thank you for this @typelogic can you please also confirm for Haiti? I updated the issue ticket to include it.

**Comment by typelogic** [comment]
Analyses result for Haiti ID MRZ.

For the TD3 type (the passport with only two rows), the check-digits of each parts and the composite check-digit all conforms to standard for TD3 MRZ. So it should follow to the same indexing used for passports (ie, PH passport).

For the TD1 type with three nows, is fully compliant with TD1 and no unusual index changes necessary. It has same pattern as of a standard MrtdTd1 indexing

**Comment by rjmangubat23** [comment]
Additional for **Cameroon ID MRZ**.

As discussed with @typelogic:

According to ICAO spec, so it is the choice of the issuing state not to completely show dob completely. In cases where it skip some part of the dob, then the issuing state use 0s in those places. 

![image](https://user-images.githubusercontent.com/11598375/128978035-636a4742-083e-4a78-a62e-c0568d8941a7.png)

Due to Cameroon National IDs omitting month and day in `dateOfBirth` we will be removing checking of date format for `dateOfBirth` specifically for Cameroon IDs only.
